src/match-path.ts, src/tsconfig-loader.ts, tests/config-loader-tests.ts, tests/match-path-tests.ts, tests/match-star-tests.ts, tests/tsconfig-loader-tests.ts, tests/tsconfig.json, yarn.lock
The tests were broken under windows since paths were hardcoded to look like unix paths.
=> Fix tests under windows (and use path.join instead of path.resolve)

src/tsconfig-loader.ts
Since release `2.7.2` there is an error if no `tsconfig.json` file is present
```
path.js:28
throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
at assertPath (path.js:28:11)
at Object.resolve (path.js:1179:7)
at resolveConfigPath (/home/nschoenmaker/projects/libs/bla/node_modules/tsconfig-paths/lib/tsconfig-loader.js:41:35)
at loadSyncDefault (/home/nschoenmaker/projects/libs/bla/node_modules/tsconfig-paths/lib/tsconfig-loader.js:19:22)
at tsConfigLoader (/home/nschoenmaker/projects/libs/bla/node_modules/tsconfig-paths/lib/tsconfig-loader.js:13:22)
at Object.configLoader (/home/nschoenmaker/projects/libs/bla/node_modules/tsconfig-paths/lib/config-loader.js:26:22)
at Object.register …
```
=> Only resolve path if tsconfig present

package.json, src/match-path-async.ts
PR to fix a forgotten return when `doneCallback` is invoked.
Could also fix the related issue of the webpack plugin: https://github.com/dividab/tsconfig-paths-webpack-plugin/issues/11
PS: I added rimraf because rm -rf doesn't work on Windows ;-)
=> Return when doneCallback is invoked

src/match-path-async.ts
Right, so this is becoming a longer story then I initially thought :)
I actually found a proper way to reproduce the issue reported in the webpack plugin: https://github.com/dividab/tsconfig-paths-webpack-plugin/issues/11 you can find it in my [own fork](https://github.com/Nayni/tsconfig-paths-webpack-plugin/blob/example-with-node-modules-fallback/example/tsconfig.json). Basically the problem is that if you let the final resolution be a node_module (which was also the case in that issue) the recursion wasn't handled properly.
It took me a while to actually figure out why this was happening but it ended up being an implicit fallthrough that would basically keep the recursion going. I've put a comment in the code to explain it explicitly.
When I fixed this up, the example I made where I …
=> Fix async recursion

src/tsconfig-loader.ts, test/config-loader-tests.ts, test/tsconfig-named.json
This is an opinionated way of solving for #31 by checking deep inside the call stack if we've received the path to tsconfig. Tests are included.
The other way of addressing this issue would require change to the loadConfig() signature, and corresponding changes to tsconfig-paths-webpack-plugin as well. I felt that'd be a larger change.
=> Fixes #31: Problem when using a custom configFile name

README.md, src/filesystem.ts, src/match-path-async.ts, src/match-path-sync.ts, test/match-path-async-tests.ts, test/match-path-sync-tests.ts
This adds support to provide a list of field names in package.json to try when resolving modules. This is useful when using `tsconfig-path` in other environments than Node, such as Webpack (see [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin) for an example).
This is a required change to tsconfig-paths in an attempt to solve the issue described in: https://github.com/dividab/tsconfig-paths-webpack-plugin/issues/20.
This PR shouldn't affect current usage, as the API still defaults to using "main", as verified by existing test cases.
=> Add support for providing a list of field names to try instead of just using "main"

package.json, src/tsconfig-loader.ts, test/tsconfig-loader-tests.ts, yarn.lock
* Switch from `JSON.parse` to `JSON5.parse`
resolves dividab/tsconfig-paths#48
=> Add support for comments and trailing commas

src/register.ts
This commit makes this resolver behave like [Node does](https://nodejs.org/api/modules.html#modules_core_modules):
> Core modules are always preferentially loaded if their identifier is passed to `require()`
Additionally this increases performance by avoiding unnecessary disk access. For example `webpack` calls `require("crypto")` in a loop.
This commit fixes #56.
=> Prefer Node's core modules over file modules

README.md, src/register.ts
register() updated to return a function to re-instate original
filename resolver.
Closes #63
=> feat: Allow cleanup of module loading

README.md, src/config-loader.ts, src/mapping-entry.ts, src/match-path-async.ts, src/match-path-sync.ts, src/register.ts, test/data/match-path-data.ts, test/mapping-entry-test.ts, test/match-path-async-tests.ts, test/match-path-sync-tests.ts
this solves part of #72 
Also makes `mainFields` configurable when using `register`.
The naming is open to bikeshedding…
=> add option to avoid adding a match-all rule

README.md
Fix typo `exeute` -> `execute`.
=> Chore: Fix typo

README.md
This functionality was implemented in #32
Direct reference:
https://github.com/dividab/tsconfig-paths/blob/47d729b39b8b2b75cb652c6a0c2d272e166764ec/src/tsconfig-loader.ts#L74-L76
=> [DOCS] Mention ability to pass the tsconfig directly

.npmignore
Seems the `.npmignore` was targeting `tests` instead of `test` - maybe the folder name was changed at some point? 🤷‍♂ 
I've also added `tslint.json` & `.nycrc.json` as they're also not needed in the published package :)
=> Update .npmignore to ignore tests and json files

package.json, yarn.lock
`json5` has provided its type definition from v2.2.0, so `@types/json5` has been deprecated.
https://github.com/json5/json5/releases/tag/v2.2.0
`json5` has dropped Node v4 support at v2, so if `tsconfig-paths` supports the version, this would be a breaking change.
Thanks!
=> deps: bump json5 to use type definition provided officially

src/tsconfig-loader.ts, test/tsconfig-loader-tests.ts
At the moment, when an extends path is specific, the extends path has to be relative to the overriding `tsconfig.json` file.
However, in the implementation of `tsc --showConfig`, it also supports search from `node_modules` in the same current directory.
e.g.
If a base file exists in `node_modules/my-package/tsconfig.base.json`.
Both
```
{
"extends": "./node_modules/my-package/tsconfig.base.json"
}
```
and 
```
{
"extends": "my-package/tsconfig.base.json"
}
```
have the same effect.
Because `tsc` behaves like this, `tsconfig-paths` should be consistent.
=> feat(tsconfig-loader): extends config from node_modules

package.json
TypeScript requires the file extension be specified in typings / types property. https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
=> Add file extenstion to typings property value

README.md, src/tsconfig-loader.ts, test/tsconfig-loader-tests.ts
Just a fresh copy of #114 to resolve its conflicts.
=> Add support for baseUrl override using TS_NODE_BASEURL env var

CHANGELOG.md, src/__tests__/data/match-path-data.ts, src/match-path-async.ts, src/match-path-sync.ts
Originally during the file path resolution, file extensions were removed
without explicit reason. This commit changes the resolution logic to keep file
extensions, with the goal to add support for modern non-js extensions
like cjs. The change however keeps /xyz/index resolves as is as they
still should resolve to /xyz.
Refs 847d314
=> fix: regard file extensions during path resolution (#133)

CHANGELOG.md, README.md, src/__tests__/tsconfig-loader.test.ts, src/tsconfig-loader.ts
close https://github.com/dividab/tsconfig-paths/issues/127
=> feat: add support for jsconfig.json

CHANGELOG.md, src/mapping-entry.ts
=> fix: don't join absolute paths with baseUrl

CHANGELOG.md, README.md, src/register.ts
I'm hitting an edge case where my `process.cwd()` is not the value I want `register` to use.
This PR will let me circumvent that programatically.
```ts
require('tsconfig-paths').register({
cwd: 'path/to/cwd',
})
```
=> feat(register): add `cwd` param

package.json
when running `yarn example:node`, the below error happened because of the wrong path: `../register.js`
```
yarn example:node        
yarn run v1.22.10
$ yarn build && cd ./example/node && ts-node -r ../register.js main.ts
$ rimraf lib && tsc -p .
Error: Cannot find module '../register.js'
Require stack:
- internal/preload
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/xxx/Lab/tsconfig-paths/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at Function.Module._preloadModules …
```
=> fix `yarn example:node` throw error

src/__tests__/config-loader.test.ts, src/__tests__/filesystem.test.ts, src/__tests__/mapping-entry.test.ts, src/__tests__/match-path-async.test.ts, src/__tests__/match-path-sync.test.ts, src/__tests__/try-path.test.ts, src/__tests__/tsconfig-loader.test.ts
This fixes the failing test called out in https://github.com/dividab/tsconfig-paths/pull/174#discussion_r863079371. It also fixes a few more failing tests. The entire test suite now passes!
I also took the opportunity to remove some commented-out assertions and remove a few unnecessary bits that had `// eslint-disable...` comments.
I would strongly encourage the maintainers to set up CI to run on pull requests, not just on master, so that errors can be caught quickly and resolved before changes are merged!
=> Fix tests and lint

package.json
After https://github.com/dividab/tsconfig-paths/pull/198, `tsconfig-paths`'s minimum Node.js version is v6. I thinks we would better specify minimum Node.js version explicitly
=> Explicitly specify minimum Node.js version

README.md, src/__tests__/data/match-path-data.ts, src/config-loader.ts, src/filesystem.ts, src/match-path-async.ts, src/match-path-sync.ts
Fixes #217.
There's some slightly repetitive code, I just wasn't sure where a common function should live, so I left the minor copy-paste.
=> Add support for nested main field selectors

src/filesystem.ts
I noticed that as the number of tried file paths goes up, Node.js spends a lot of time preparing a native exception to throw over the JS barrier. I narrowed this down to be a result of relying on the `fs.statSync` call in `fileExistsSync` to determine whether or not the file exists on top of whether or not it is actually a file. 
Prepending a call to `fs.existsSync` allows us to skip the preparation time of throwing an exception at the cost of causing another IO hit. There is ostensibly some sort of tradeoff but for the large monolithic app I work on, this shaves off the vast majority of the boot and hot reload time.[1]
Happy to discuss / prepare a more detailed breakdown if necessary.
1: 6x improvement in boot time on ~6k JS source files
=> Skip stat call / throwing an exception when source files don't exist

package.json, yarn.lock
Versions of JSON5 < 2.2.2 are susceptible to CVE-2022-46175.
This PR bumps this project's dependency to 2.2.2, which resolves this vulnerability. There are no other changes / no breaking changes in the version bump ([changelog](https://github.com/json5/json5/blob/main/CHANGELOG.md#v222-code-diff))
=> Bump JSON5 dependency to 2.2.2 to fix CVE-2022-46175

package.json, yarn.lock
Needs a v3 branch created from v3.14.1 tag first then we can change the target branch of this PR.
=> bump jsot5 to fix CVE-2022-46175

src/__tests__/tsconfig-loader.test.ts, src/tsconfig-loader.ts
Fixes #244.
TypeScript 5.0 added support for defining "extends" as an array of strings. This commit adds support for this use case.
It's important to note that even with this change, "baseUrl" and "paths" are still always being completely overwritten if a later tsconfig redefines any of those values.
This might be confusing because a tsconfig may define "baseUrl=value1" and its own set of "paths" based on that baseUrl, but if a later tsconfig defines its own "baseUrl=value2", the overall config ends up becoming "baseUrl=value2" with the "paths" from the first config.
This behaviour hasn't changed even when "extends" is an array of strings, so this commit maintains this behaviour.
=> Add support for extends as array of strings.

.npmignore, package.json
I noticed that [despite the `.npmignore` file of this project](https://github.com/dividab/tsconfig-paths/blob/11b774d994b897c6c8e87dda57375a285813731d/.npmignore), files from [the `__tests__/` directory](https://github.com/dividab/tsconfig-paths/tree/11b774d994b897c6c8e87dda57375a285813731d/src/__tests__) are still being published:
<details>
<summary>Proof</summary>
</details>
After looking at #137 and #186, and reading [For the love of god, don’t use .npmignore](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d) as well as the [npm docs "Developer Guide"](https://docs.npmjs.com/cli/v9/using-npm/developers), I came to the following conclusion: Using both [`"files"`](https://github.com/dividab/tsconfig-paths/blob/11b774d994b897c6c8e87dda57375a285813731d/package …
=> Use an allowlist-based .npmignore file

src/__tests__/data/match-path-data.ts, src/__tests__/try-path.test.ts, src/try-path.ts
This resolution requires relative/mapped import paths to end with .js
This PR detects if a path ends with `.js` and if so adds more extension type paths to try, that omit this extension when attaching additional extensions to match the actual existing files.
Reference https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs
Should resolve https://github.com/dividab/tsconfig-paths/pull/213 (edit 1: wrong issue sorry, edit 2: actually I believe this **might** resolve that issue as well) & https://github.com/aleclarson/vite-tsconfig-paths/issues/59
=> Fix missing paths when using typescript's module nodenext feature

src/__tests__/tsconfig-loader.test.ts, src/tsconfig-loader.ts
TypeScript 5.0 added support for defining "extends" as an array of strings. This commit adds support for this use case.
This is a backport of #245, which fixes:
- https://github.com/dividab/tsconfig-paths/issues/259
- https://github.com/import-js/eslint-plugin-import/pull/2447#issuecomment-1653491616
- https://github.com/import-js/eslint-plugin-import/issues/2890
This should be releasable as a minor version, e.g. 3.15.0
=> Add support for extends as array of strings to v3 (backport of #245)

README.md
This updates the readme to include bun install alongside yarn and npm. Also changed the syntax highlighting to bash so it looks nicer.
=> docs: update readme to include bun install
